package cn.com.bright.workflow.api;

import org.activiti.engine.FormService;

public interface IformService extends FormService {
	
	

	  /** Rendered form generated by the default build-in form engine for starting a new process instance. */
	  Object getRenderedStartForm(String processDefinitionId);

	  /** Rendered form generated by the given build-in form engine for starting a new process instance. */
	  Object getRenderedStartForm(String processDefinitionId, String formEngineName);
	  
	  /** Rendered form generated by the default build-in form engine for completing a task. */
	  Object getRenderedTaskForm(String taskId);

	  /** Rendered form generated by the given build-in form engine for completing a task. */
	  Object getRenderedTaskForm(String taskId, String formEngineName);
	  
	  
	  Object getRenderedProcessForm(String processInstanceId, String formEngineName);

}
